config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :posts do
    resources :comments, only: %i[new create destroy] do
      resources :replies, only: %i[new create destroy]
    end
  end

  root to: 'pages#index'
  match '/home', to: 'pages#home', via: [:get]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_many :replies

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :user_id, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment, optional: true
  belongs_to :user, optional: true
  belongs_to :posts, optional: true

  validates :user_id, presence: true
  validates :comment_id, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # call strong params
  before_action :configure_permitted_parameters, if: :devise_controller?

  # strong params
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :handle, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :handle, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :handle, :username, :current_password, :password, :password_confirmation, :remember_me)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to home_path
    else
      flash[:notice] = 'Unable to comment on this post'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :body, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all
  end

  def home
    @posts = Post.all
    @new_post = Post.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to home_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to home_path
    else
      flash[:alert] = 'Unable to create post'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to home_path
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.replies.new
  end

  def create
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.replies.new(reply_params)
    @reply.user_id = current_user.id
    if @reply.save
      redirect_to home_path
    else
      flash[:notice] = 'Unable to reply to this comment'
      render :new
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:comment_id, :body, :post_id, :user_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    configure_permitted_parameters
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # def new
  #   super
  # end

  # def create
  #   super
  # end

  def destroy
    sign_out(current_user)
    redirect_to root_path
  end

  # private

  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/new.html.erb
<div class="container">
  <h2>Comment on a post</h2>
  <hr style="border: none; border-bottom: 1px solid black;">
  <%= simple_form_for @comment, url: post_comments_path do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :body %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Create' %>
      <%= link_to "Cancel", :back %>
    </div>
  <% end %><hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    #post-media {
      margin-bottom: -21px;
    }
    .panel-body {
      width: 100%;
    }
    .media-body .form-control {
      height: 35px;
    }
  </style>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Welcome <%= current_user.username %></h1>
  <p><%= link_to 'Create new post', new_post_path %> |
    <%= link_to "Log out", destroy_user_session_path, method: :delete %> |
    <%= link_to "Edit profile", edit_user_registration_path %>
  </p>
  <hr style="border: none; border-bottom: 1px solid grey;">
  <% @posts.each do |post| %>
    <h4><%= User.find(post.user_id).username %> -<span class="post-time"> Created <%= time_ago_in_words(post.created_at) %> ago</span> </h4>
    <h5><%= User.find(post.user_id).handle %></h5>
    <p><%= post.content %></p>
    <%= link_to 'Show comments', post_path(post.id)%> |
    <%= link_to 'Add comment', new_post_comment_path(post.id)%>
    <% if User.find(post.user_id).username == current_user.username %> |
      <%= link_to "Delete", post_path(post.id), method: :delete %> |
      <%= link_to 'Edit post', edit_post_path(post.id)%>
    <% end %><br> <br>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="container">
	<% if !user_signed_in? %>
		<div class="container">
			<h1>Home page if not signed in</h1>
			<%= link_to 'Sign up', new_user_registration_path, class: 'nav-item nav-link' %> |
			<%= link_to "Sign in", new_user_session_path, class: 'nav-item nav-link' %>
			<hr style="border: none; border-bottom: 1px solid black;">
			<% @posts.each do |post| %>
				<h4><%= User.find(post.user_id).username %> -<span class="post-time"> Created <%= time_ago_in_words(post.created_at) %> ago</span> </h4>
				<h6><%= User.find(post.user_id).handle %></h6>
				<p><%= post.content %></p>
				<%= link_to 'Show comments', post_path(post.id)%><br>
			<br>
			<% end %>
		</div>
	<% else %>
	  <script>document.location = "/home" </script>‘
	<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h2>Edit your post</h2>
  <hr style="border: none; border-bottom: 1px solid black;">
  <%= simple_form_for @post do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Create' %>
      <%= link_to "Cancel", :back %>
    </div>
  <% end %><hr>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2>Create a message</h2><hr>
  <%= simple_form_for @post do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Create' %>
      <%= link_to "Cancel", :back %>
    </div>
  <% end %><hr>
</div>

app/views/posts/show.html.erb
<div class="container">
  <% if !user_signed_in? %>
    <h2><%= @post.content %></h2>
    <%= link_to 'Back', :back %>
    <hr style="border: none; border-bottom: 1px solid black;">
     <div id='comments'>
      <% @post.comments.each do |comment|%>
      <div class='comment'>
        <h4><%= User.find(comment.user_id).username %> -<span class="post-time"> Created <%= time_ago_in_words(comment.created_at) %> ago</span> </h4>
        <p><%= comment.body %></p><hr>
      </div>
      <% end %>
    </div>
  <% else %>
    <h2><%= @post.content %></h2>
    <%= link_to 'Add comment', new_post_comment_path(@post.id)%> |
    <%= link_to 'Back', :back %>
    <hr style="border: none; border-bottom: 1px solid black;">
     <div id='comments'>
      <% @post.comments.each do |comment|%>
      <div class='comment'>
        <h4><%= User.find(comment.user_id).username %> -<span class="post-time"> Created <%= time_ago_in_words(comment.created_at) %> ago</span> </h4>
        <p><%= comment.body %></p>
        <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete %> |
        <%= link_to 'Reply', new_post_comment_reply_path(@post.id, comment.id)%>
        <div class="container" id='reply'>
          <% comment.replies.each do |reply| %>
          <div class="reply">
            <h6><%= User.find(comment.user_id).username %> - <span class="post-time"> Created <%= time_ago_in_words(reply.created_at) %> ago</span></h6>
            <p><small><%= reply.body %></small></p>
          </div>
          <% end %>
        </div><hr>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/replies/new.html.erb
<div class="container">
  <h2>Reply to a comment</h2>
  <hr style="border: none; border-bottom: 1px solid black;">
  <%= simple_form_for @reply, url: post_comment_replies_path do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :body %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Create' %>
      <%= link_to "Cancel", :back %>
    </div>
  <% end %><hr>
</div>